### ISSUE TITLE
Brush stops painting randomly

### ISSUE THREAD

**Issue by terrybrashaw** [serge-rgb/milton#24]
**Milton:** 1.2.7
**OS:** Windows 8.1

When doing a long stroke, the brush will stop painting after a short time.

Video: https://www.youtube.com/watch?v=vvfMNK6Xe1s

In the video, I am holding `Mouse 1` and drawing squiggles until the brush stops painting. _I am not releasing `Mouse 1` until the brush stops painting._

At the end of the video you'll notice I present the same issue occurring with the eraser.

**Comment by serge-rgb** [comment]
There's a hard limit on the number of points a stroke can have. I'm guessing that you have a higher-end wacom tablet than I have, with a higher sample rate. That would explain why the maximum length is much more on My Machine®. 
I remember that I reduced the maximum size at one point because of an OpenGL limitation, but that was a long time ago and the limitation might not be there. I'll update this issue after it's fixed (or if it can't be fixed)
Thanks!

**Comment by ApoorvaJ** [comment]
Do let me know if this is an issue with EasyTab, and whether you want to push an update upstream. :)

**Comment by serge-rgb** [comment]
Not a problem with EasyTab :)

**Comment by serge-rgb** [comment]
I'm setting this as a WontFix. It's an arbitrary limit, but changing it would mess with the file format. That said, I'd be willing to reconsider if this is a serious problem for someone,
