### ISSUE TITLE
Crash on linux with intel graphics card

### ISSUE THREAD

**Issue by jatha** [serge-rgb/milton#37]
The bug occured after executing a fresh build from  f685ab9. I just ran it by doing:
```
git clone https://github.com/serge-rgb/milton
cd milton
make
cd build
./milton
```
A window was showing up, but it instantly crashed.
Im running arch linux and im having sdl2 installed.
[crash_log.txt](https://github.com/serge-rgb/milton/files/724524/crash_log.txt)

**Comment by jatha** [comment]
It maybe has something to do with this commit:
https://github.com/abrasive/milton/commit/1660b173c07dc9a69e21648b0276a1d80fe02150

**Comment by serge-rgb** [comment]
I have also hit this bug one one Linux machine with Mesa. Thanks for reporting! Will close the issue when it's fixed.

**Comment by Mischanix** [comment]
On the topic of intel issues, I had an issue with the outline shader:

This was my fix:  <https://github.com/Mischanix/milton/commit/21a0f20876ee10cdfa57068caf270a8cd8b91697#diff-8626b98297260f641bb7efcc5ec5a8df>

Ended up using some random number for gl_Position.w and caused the outline to (glitchily) render on a screen coord space of [-0.5,0.5] instead of [-1,1].

**Comment by serge-rgb** [comment]
@jatha I think your issue should be fixed by a recent commit. Please let me know if it isn't and I will reopen the issue.
@Mischanix Thanks! I'm glad you found/fixed this.
