### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by DomenicWalther** [serge-rgb/milton#7]
d:\programs\milton-master\src\persist.c(450): error C2220: warning treated as error - no 'object' file generated
d:\programs\milton-master\src\persist.c(450): warning C4242: 'function': conversion from 'u64' to 'size_t', possible loss of data
   [FATAL] -- ... error building Milton

Using the Developer command Prompt for VS2015

**Comment by serge-rgb** [comment]
Thanks. I am getting the same error, and disabled a couple of warnings.
I did not know this before now, but the Developer Command Prompt only enables an x86 toolset, and the build script is setup to link as x64. I will change the readme to reflect this. Sorry for the waste of time. 
FWIW. You can open a command prompt and run 
```
scripts\vcvars.bat
build.bat
```
and it should build fine, since you have VS2015 installed.

**Comment by DomenicWalther** [comment]
Thanks, it's working now! Everyone reading this: If you got this error make sure you run the clean.bat which will delete the build folder (you can just delete it but the batch way is way cooler ;)) to make it work.  
Also be reminded that you may have to change the Path to your Visual Studio Installation in order to make the vcvars.bat work. 
Great program btw ;)

**Comment by serge-rgb** [comment]
Thanks! But you did bring up a lefitimate issue - the VS2015 developer prompt is x86 only and milton is x64 only at the moment. The readme should reflect that :)
